### ISSUE TITLE
CarID values above decimal 60 (hex 0x3C) don't seem to work

### ISSUE THREAD

**Issue by GearheadLydia** [nlgzrgn/NFSU2CarSoundTuner#1] opened 2020-05-06 19:43 UTC
I'm currently working on converting all of the Most Wanted and Carbon sounds to Underground 2 in sequential order. I'm currently stuck on lot_elise and lam_gallardo, because CarID values 61 and 62 don't seem to work. Is this a hard-coded limit of Underground 2, or an issue with the application?

(If the actual Most Wanted ABK files above 60 are formatted in a way Underground 2 can't read, then obviously that's an entirely different story.)

EDIT: Okay, so it's definitely not the way the MW ABK files are formatted. Copying one to an index lower than 60 and changing its internal ID (located at 0x0012AC in EE ABKs and at 0x000F7C in SPU ABKs) to match makes MW ABKs work.

**Comment by RAZORXKHARA33** [comment] 2020-05-12 09:07
I can confirm that this is happening for me, too, as I tried with the TVR Tuscan sound (ID 65) and that didn't work. How did you change the internal ID in the ABK files? I don't think it'll be possible to do the Carbon sounds because the ABKs use a different format AFAIK that even MW can't read. I already tried porting sounds from Carbon over to MW and had to reuse ABKs because of this. Unless you've had better luck with that...

**Comment by GearheadLydia** [comment] 2020-05-12 20:45
@RAZORXKHARA33

I haven't tried Carbon ABKs yet.

If you want to change the ID of a Most Wanted ABK, open it with a hex editor and do a search for "9CFFFFFF". You will then find an address where, very nearby, there is a hex number corresponding to the decimal CarID number. (So for decimal number 32, it'll be hex 20.) Change it there. Again, for EE ABKs, it's usually around 0x000012AC (you can hit "go to" on most hex editors), and in SPU ABKs it's usually aruond 0x00000F7C. SWTN ABKs also have this.

**Comment by RAZORXKHARA33** [comment] 2020-05-12 21:53
That is working for the most part, but the sweeteners still seem to be missing. I made sure to change those values accordingly, too, but no dice. Could the index issue affect sweeteners differently?

**Comment by RAZORXKHARA33** [comment] 2020-12-01 19:09
This workaround now works 100%, sweeteners and sputters are playing properly for the newly added sounds. However, the index limit appears to still be here overall, since once I changed the indexes back to what they were in MW 05 (making sure to update the files in CarSoundData accordingly), I lost EE (constant RPM, idle, and rev limiter), Sputters, and Sweeteners.

**Comment by nlgxzef** [comment] 2020-12-10 14:47
Looks like I had to fix more limits. Can you test your new sounds with this .asi file?

[NFSU2CarSoundTuner.zip](https://github.com/nlgzrgn/NFSU2CarSoundTuner/files/5673542/NFSU2CarSoundTuner.zip)

**Comment by RAZORXKHARA33** [comment] 2020-12-11 10:39
@nlgzrgn Can confirm this works. I tested with the the following IDs and assignments: car 63 (diablo, used for NSX stages 2 and 3), car 65 (tuscan, used for NSX stage 1), car 72 (corvette_z06, used for GTO stock and stage 1), and car 74 (corvette_z06_dyn_v2, used for GTO stages 2 and 3). It should work for all of the NFSMW sounds now.

**Comment by nlgxzef** [comment] 2020-12-11 13:09
Thanks! I've updated the mod with the fixes from the test build. I think I can safely close this issue now.

**Closed as completed by nlgxzef** 2020-12-11 13:09 UTC
